version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.0
  build:
    commands:
      - cd talk-demos/appdeployment/SampleApp
      - dotnet publish -c release -o ./build_output ./app/app.csproj
artifacts:
  files:
    - build_output/*
    - appspec.yml
    - installApp.sh
  base-directory:
    ./talk-demos/appdeployment/SampleApp